<?php
echo "<h2 class='text-center'>Początki</h2>".
            "<p>Historia polskiego lotnictwa sięga roku 1918, czasu I wojny światowej. Właściwie proces powstawania lotnictwa rozpoczął się jeszcze przed odzyskaniem niepodległości. Trzeba tu zaznaczyć, że polskie formacje powstawały na terenach zagranicznych, jednak Polacy, którzy tam służyli, stanowili trzon powstałego później lotnictwa polskiego. Polski, wyniszczonej wojną, nie było stać wtedy na jakąkolwiek produkcję na szerszą skalę. Sprzęt, który używano w budujących się dopiero polskich formacjach, pochodził z arsenału państw, w których formacja powstawała. Były to także zdobycze z terenów wyzwolonych i zakupów realizowanych poza granicami.".

"Warto podkreślić, że wiele z nich zdobyto właśnie w Polsce, m.in. na lotniskach w Warszawie i Poznaniu-Ławicy, Krakowie i Lwowie. Były to głównie samoloty wycofane z jednostek bojowych, mocno wysłużone, wymagające remontów. Tak więc lotnictwo polskie używało sprzętu produkcji niemieckiej, austriackiej, francuskiej, rosyjskiej, angielskiej.".
"Ale ponieważ Polacy jak wiadomo są pomysłowi w lotnictwie używali też „składaków” montowanych z podzespołów pochodzących z różnych typów samolotów lub z dostarczonych wraków.</p>".

"<p>Jak daje się zauważyć, początki lotnictwa polskiego nieodłącznie wiążą się z lotnictwem wojskowym. Pierwszy lot bojowy polskiego samolotu odbył się 5 listopada 1918 roku. Równocześnie utworzono wtedy Dowództwo Wojsk Lotniczych-pierwszą organizację lotnictwa wojskowego.".
"Lotnictwo polskie, które rozpoczynało swój rozwój, wymusiło powstanie bazy szkoleniowej. Pierwszy taki ośrodek powstał w Ławicy koło Poznania, gdzie zorganizowano Wyższą Szkołę Lotniczą, szkolącą pilotów wojskowych.".
"W 1933 roku eskadry myśliwskie otrzymały nowy sprzęt w postaci samolotów polskiej konstrukcji P.7, a w 1935 rozpoczęto przezbrajanie eskadr na nowsza wersję P.11. Jednak już po czterech latach, P.11 były przestarzałe w porównaniu z konstrukcjami zagranicznymi.".
"W marcu 1939 Sztab Lotnictwa przy Sztabie Głównym przy pojawiających się pogłoskach możliwości wybuchu kolejnej wojny, przystąpił do przetwarzania sił lotniczych z organizacji pokojowej na wojenną. Nie udało się to w pełni. Na początku II wojny światowej lotnictwo polskie dysponowało zaledwie 400 samolotami, w dużej mierze przestarzałymi technicznie.</p>".
"<image class='img-fluid rounded-3 mx-auto d-flex justify-content-center' src='/histobrazy/Gdynia.jpg' alt='gdy'>".
"<p class='text-center'>Lot na Gdynią - około roku 1920</p>".
"<h2 class='text-center'>II wojna swiatowa</h2><p>Polskie lotnictwo w czasie II wojny światowej przeżywało chwile wzlotów i upadków związane przede wszystkim z powodzeniem konkretnych bitew i operacji. Sukcesy były uzależnione w dużej mierze od sprzętu, jakim dysponowali polscy piloci. W czasie Wojny Obronnej 1939 roku siły powietrzne nie były w stanie stawić czoła liczebniejszym i lepiej wyposażonym Niemcom, ale podjęły się zaciętej walki z Luftwaffe. Tylko część polskich samolotów została utracona lub uszkodzona zanim piloci poderwali je do akcji, choć do dzisiaj pokutuje mylne przekonanie o bezradności Polaków i zniszczeniu samolotów na lotniskach. </p>".

"<h3 class='text-center'>Służba w szeregach aliatnów</h3><p>Po upadku Francji znaczna część polskich pilotów została ewakuowana do Wielkiej Brytanii. Na mocy szeregu umów wojskowych, których podsumowaniem było porozumienie z 5 sierpnia 1940 roku, przystąpiono do odbudowy Polskich Sił Powietrznych. Dowódcą PSP został gen. Józef Zając, z kolei stanowisko Inspektora PSP od lipca 1940 roku pełnił gen. Stanisław Ujejski, którego w sierpniu 1943 roku zastąpił gen. Mateusz Iżycki. Choć PSP były podporządkowane Royal Air Force, miały pewną niezależność, posiadając własne mundury, odznaczenia, wydzielone dowództwo. Spory kompetencyjne miały trwać do końca wojny i były najczęściej związane z odmiennymi wizjami wykorzystania Polaków w boju. Już 1 lipca 1940 roku został sformowany 300. Dywizjon Bombowy, 22 lipca 301. Dywizjon Bombowy i wreszcie 10 lipca 302. Dywizjon Myśliwski oraz 2 sierpnia najbardziej znany i utytułowany 303. Dywizjon Myśliwski Warszawski im. Tadeusza Kościuszki.</p>".

"<p>Latem 1940 roku nie ulegało wątpliwości, że Polacy powinni wziąć udział w obronie powietrznej Wielkiej Brytanii w związku ze zmasowanym atakiem niemieckich bombowców i myśliwców. Ostatecznie w czasie bitwy walczyło 145 polskich lotników myśliwskich służących zarówno w polskich jak i brytyjskich dywizjonach. Dodatkowo w 303. Dywizjonie służyło dwóch czeskich lotników, których zwycięstwa są na ogół zaliczane do bilansu załóg polskich. Sierż. Josef František, mimo czeskiego pochodzenia, wielokrotnie deklarował polskość. Obok nich alianckie lotnictwo wspierało 124 pilotów dywizjonów bombowych 300 i 301, którzy operowali niemal w całym okresie bitwy, dokonując bombardowań celów strategicznych na kontynencie. Batalia odznaczała się niezwykłym natężeniem walk. Alianci nie nadążali z uzupełnianiem strat wśród zestrzeliwanych lotników, toteż polska pomoc okazała się szczególnie wydatna, zwłaszcza w obliczu znakomitych wyników polskich myśliwców. Swoiste rekordy ustanawiali piloci 303. Dywizjonu. Mimo iż Polacy stanowili zaledwie 5% wszystkich alianckich lotników walczących w bitwie, odpowiadali za 12% zniszczonych niemieckich maszyn. Łącznie zestrzelili 170 samolotów, z czego aż 126 zwycięstw przypadło w udziale lotnikom 303. Dywizjonu. Łączne straty Polaków obejmowały 29 zabitych (w tym František). Momentem szczególnym bitwy o Wielką Brytanię był 15 września, gdy Niemcy przystąpili do zmasowanego nalotu na angielskie miasta. Polacy z 303. i 302. Dywizjonu strącili łącznie 23 maszyny wroga. Po zakończeniu bitwy premier Winston Churchil wypowiedział słynne słowa:".
"<q class='font-italic'><strong>Nigdy w dziejach wojen tak liczni nie zawdzięczali tak wiele tak nielicznym</strong></q> co powszechnie odbierano jako hołd złożony bohaterskim lotnikom. Polacy cieszyli się w tym czasie niezwykłym szacunkiem i poważaniem wśród sojuszników, jak również wśród brytyjskiego społeczeństwa, które doceniało wysiłek lotników i ocalenie wyspy przed niemiecką agresją.</p>".

"<p>Sukcesy powietrzne PSP były katalizatorem dalszego rozwoju polskich jednostek. Jeszcze w sierpniu 1940 roku powstały dywizjony 304. bombowy, 307. nocny myśliwski i 306. myśliwski, a miesiąc później kolejne - 305. bombowy i 308. myśliwski. W październiku powołano 309. myśliwski. W kolejnych latach tworzono 315. myśliwski, 316. myśliwski, 317. myśliwski (wszystkie w 1941 roku), 318. myśliwsko-rozpoznawczy (1943) i wreszcie 663. Dywizjon Samolotów Artylerii (wrzesień 1944). Obok nich warto wymienić utworzoną w 1940 roku Polską Eskadrę Balonową jako jednostkę balonów zaporowych służących ochronie Wielkiej Brytanii.</p>".

"<p>Przez lata Polacy byli angażowani do większości najważniejszych operacji alianckiego lotnictwa. Wraz z upływem czasu i zmianą sytuacji na froncie większy nacisk był kładziony na operacje lotnictwa bombowego w nalotach na niemieckie miasta. Polacy uczestniczyli także w operacjach osłonowych w czasie ważnych alianckich desantów, w tym lądowania w Normandii. W listopadzie 1943 roku została sformowana 1586. Eskadra Specjalnego Przeznaczenia grupująca polskich pilotów 138. Dywizjonu RAF. Jej piloci uczestniczyli przede wszystkim w misjach zaopatrzeniowych i przerzutowych do okupowanej Polski. Jednostka poniosła szczególnie wysokie straty w czasie próby zrzutów dla oddziałów Polskiego Podziemia walczących w czasie Powstania Warszawskiego.<p>".
"<image class='img-fluid rounded-3 mx-auto d-flex justify-content-center' src='/histobrazy/Lewkowicz.jpg' alt='lewk'>".
"<p class='text-center'>Kpt. Janusz Lewkowicz z 309 Dywizjonu Myśliwskiego stoi przy swoim Mustangu, za którego sterami wykonał pionierski lot ze Szkocji do Norwegii (wrzesień 1942).</p>".

"<p>Ważnym i ciekawym elementem historii PSP jest powołanie i zaangażowanie Polskiego Zespołu Myśliwskiego nazywanego popularnie Cyrkiem Skalskiego od nazwiska dowódcy Stanisława Skalskiego. Elitarna grupa została sformowana w lutym 1943 roku i brała udział w walkach na froncie afrykańskim. Jej piloci odnieśli 25 pewnych zwycięstw powietrznych w stosunkowo krótkim okresie działania, bijąc rekordy skuteczności wśród jednostek alianckich. W maju 1943 roku kampania została zakończona w związku z kapitulacją sił niemiecko-włoskich. </p>";

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

